import type { Metadata } from "next";
import "./globals.css";
import {
    Amiri,
    Cormorant_Garamond,
    Great_Vibes,
    Lora,
} from "next/font/google";

const cormorant = Cormorant_Garamond({
    variable: "--font-cormorant",
    subsets: ["latin"],
});

const greatVibes = Great_Vibes({
    weight: "400",
    variable: "--font-great-vibes",
    subsets: ["latin"],
});

const lora = Lora({
    variable: "--font-lora",
    subsets: ["latin"],
});

const amiri = Amiri({
    weight: ["400", "700"],
    variable: "--font-amiri",
    subsets: ["arabic"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
    return (
        <html
            lang="en"
            className={`${cormorant.variable} ${greatVibes.variable} ${lora.variable} ${amiri.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">{children}</body>
        </html>
    );
}
